# Input
content_images_dir: "data/content-images"
# content_img_name: "berlin_000000_000019_leftImg8bit.jpg"
content_img_name: "berlin_000000_000019_leftImg8bit_rain.jpg"
# content_img_name: "lion.jpg"

style_images_dir: "data/style-images"
# style_img_name: "rain_storm-002.jpg"
style_img_name: "vg_starry_night.jpg"

# Output
save_dir: "data/output-images"
saving_freq: 10

# Optimization
img_hw: [400, 400]
model: "vgg19" # ["vgg16", "vgg19"]
optimizer: "adam" # ["lbfgs", "adam"]
init_method: "content" # ["random", "content", "style"]
loss_weights:
  content_weight: 1.0e+5
  style_weight: 3.0e+4
  tv_weight: 1.0e+0
num_of_iterations: 500 # lbfgs: 1000, adam: 3000
