# Input
content_images_dir: "data/content-images"
content_img_name: "berlin_000000_000019_leftImg8bit.jpg"
# content_img_name: "lion.jpg"

style_images_dir: "data/style-images/windshield_droplets"
style_img_names:
  # art
  # - "vg_starry_night.jpg"
  # rain_storm
  # - "rain_storm-001.jpg"
  # - "rain_storm-002.jpg"
  # - "rain_storm-005.jpg"
  # windshield_droplets
  # - "rain_storm-019.jpg"
  # - "rain_storm-207.jpg"
  # - "rain_storm-213.jpg"
  # - "rain_storm-283.jpg"
  - "rain_storm-443.jpg"
  # - "rain_storm-740.jpg"
  # - "rain_storm-748.jpg"
  # - "rain_storm-779.jpg"
  # snowing
  # - snow_storm-079.jpg
  # - snow_storm-285.jpg
  # - snow_storm-251.jpg
  # - snow_storm-255.jpg
  # - snow_storm-111.jpg
  # - snow_storm-301.jpg
  # - snow_storm-360.jpg
  # splash
  # - rain_storm-004.jpg
  # - rain_storm-009.jpg
  # - rain_storm-034.jpg
  # - rain_storm-082.jpg
  # - rain_storm-233.jpg
  # - rain_storm-343.jpg
  # - rain_storm-005.jpg
  # - rain_storm-026.jpg
  # - rain_storm-038.jpg
  # - rain_storm-158.jpg
  # - rain_storm-241.jpg
  # - rain_storm-489.jpg
  # - rain_storm-007.jpg
  # - rain_storm-030.jpg
  # - rain_storm-070.jpg
  # - rain_storm-225.jpg
  # - rain_storm-339.jpg
  # - rain_storm-688.jpg


# Output
save_dir: "data/output-images"
saving_freq: 100

# Optimization
img_hw: [400, 400]
model: "vgg19" # ["vgg16", "vgg19"]
optimizer: "adam" # ["lbfgs", "adam"]
Adam:
  lr: 1
loss_weights:
  content_weight: 1.0
  style_weight: 1.0
  tv_weight: 0.0
num_of_iterations: 3000
